services:
  - type: web
    name: spacewave-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python network/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
